# -*- coding: utf-8 -*-
"""Python practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hKgiHe0n-FSlNs_nzMC5t9sWulzYx0gx

# **Python practice problems 1**
"""

#1.Write a Python program which accepts the radius of a circle from the user and compute the area.
import math

radius = float(input("Enter the radius of the circle: "))

area = math.pi * radius ** 2
print("The area of the circle with radius", radius, "is:", area)

#2.Write a Python Program to accept the details of a student like name, rollnumber and mark and display it.
name = input("Enter student's name: ")
roll_number = input("Enter student's roll number: ")
marks = float(input("Enter student's marks: "))

print("\nStudent Details:")
print("Name:", name)
print("Roll Number:", roll_number)
print("Marks:", marks)

#3.Write a Python program to get the largest number from a list.
numbers = [int(x) for x in input("Enter numbers: ").split(',')]
largest_number = max(numbers)
print(f"{largest_number} is the largest number.")

#4.Given a range of first 10 numbers, write a Python program to iterate from start number to the end number and print the sum of the current number and previous number.
previous_number = 0
for current_number in range(1, 11):
    sum_of_previous_and_current = previous_number + current_number
    print(f"Current number: {current_number}, Previous number: {previous_number}, Sum: {sum_of_previous_and_current}")
    previous_number = current_number

#5.Write a Python program to print only those numbers which are divisible of 5.
for number in range(1, 101):
    if number % 5 == 0:
        print(number)

#6.Write a Python program to check whether a number is prime or not.
number = int(input("Enter the number: "))

is_prime = number > 1 and all(number % i != 0 for i in range(2, int(number ** 0.5) + 1))
print(f"{number} is {'prime' if is_prime else 'not prime'}")

#7.Write a Python program to reverse a list using for loop.
input_list = input("Enter: ").split(',')
reversed_list = []

for i in range(len(input_list) - 1, -1, -1):
    reversed_list.append(input_list[i])

print("Reversed List:", ','.join(reversed_list))

#8.Write a Python program to print the following pattern.
#*
#**
#***
#****
for i in range(1, 5):
    print('*' * i)

#9.Write a Python program to find the maximum of three numbers
Sample input:
numbers = [int(x) for x in input("Enter three numbers : ").split(',')]
maximum = max(numbers)
print("The maximum of the three numbers is:", maximum)

#10. Write a Python program to construct the following pattern, using a nested for loop.
#*
#**
#***
#****
#*****
#****
#***
#**
#*
for i in range(1, 6):
    print('*' * i)

for i in range(4, 0, -1):
    print('*' * i)



"""# **Python practice problems 2 **"""

#1.Write a Python program to accept a string value from the user and display the count of each character in that string.
string = input("Enter a string value: ")
char_count = {}

for char in string:
    char_count[char] = char_count.get(char, 0) + 1

print("Sample output:", ", ".join([f"{char}={count}" for char, count in char_count.items()]))

#2.Write a Python function to find the maximum of three numbers Sample
def find_maximum(a, b, c):
    return max(a, b, c)

num1, num2, num3 = map(int, input("Enter three numbers: ").split(','))
maximum = find_maximum(num1, num2, num3)
print("The maximum of the three numbers is:", maximum)

#3.Write a Python function called exponent(base,exp) that returns an integer value of base raises to the power of exp
def exponent(base, exp):
    return base ** exp

base = int(input("Enter the base: "))
exp = int(input("Enter the exponent: "))
result = exponent(base, exp)
print("Result:", result)

#4.Write a Python function that takes a positive integer and returns the sum of the cube of all the positive integers smaller than the specified number.
def sum_of_cubes(n):
    return sum(i ** 3 for i in range(1, n))

num = int(input("Enter a positive integer: "))
result = sum_of_cubes(num)
print("Sum of cubes of positive integers smaller than", num, "is:", result)

#5.Write a Python program which iterates from 1 to 10. For multiples of 2, print “Fizz” instead of the number and for the multiples of 5, print “Buzz”.
#For numbers which are multiples of both 2 and 5, print “FizzBuzz”.
for num in range(1, 11):
    if num % 2 == 0 and num % 5 == 0:
        print("FizzBuzz")
    elif num % 2 == 0:
        print("Fizz")
    elif num % 5 == 0:
        print("Buzz")
    else:
        print(num)

#6.Write a Python program to find the most frequent item in a list of numbers
from collections import Counter

numbers = [int(x) for x in input("Enter numbers: ").split(',')]
most_frequent = Counter(numbers).most_common(1)[0][0]
print("The most frequent item in the list is:", most_frequent)

#7.Write a Python program to find the sum of squares of the numbers in a list.
numbers = [int(x) for x in input("Enter numbers: ").split(',')]
sum_of_squares = sum(x ** 2 for x in numbers)
print("The sum of squares of the numbers in the list is:", sum_of_squares)

#8.Write a Python program using for loop that will iterate from 1 to 15.
#For each iteration, check if the current number is odd or even, and display the message to the screen as odd or even
for number in range(1, 16):
    if number % 2 == 0:
        print(f"{number}-even")
    else:
        print(f"{number}-odd")

#9.Write a Python program to convert temperatures to and from Celsius Fahrenheit
temperature_fahrenheit = float(input("Temperature in Fahrenheit: "))
print("Temperature in Celsius:", (temperature_fahrenheit - 32) * 5 / 9)

temperature_celsius = float(input("Temperature in Celsius: "))
print("Temperature in Fahrenheit:", (temperature_celsius * 9 / 5) + 32)

#10.Write a Python function to calculate the factorial of a number (a nonnegative integer).
#The function accepts the number as an argument.
def factorial(n):
    if n == 0:
        return 1
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

number = int(input("Enter a nonnegative integer: "))
print("Factorial of", number, "is:", factorial(number))